version: '3.8'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-db:/var/lib/mysql
  api:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  # client:
  #   build:
  #     context: ./Front/hospifront
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env

volumes:
  mysql-db:
